 const gameRoster=roster.map((d,index)=>({...d,rank:index+1,tier:d.gap>=10?'legendary':d.gap>=4?'epic':d.gap>=0?'rare':'common'}));
 const gameById=Object.fromEntries(gameRoster.map(d=>[d.key,d]));
 const fantasySelections={...(window.openai?.widgetState?.privateContent?.fantasySelections||{})};
 const titleCase=s=>s[0].toUpperCase()+s.slice(1);
 function cardMarkup(d,key) {
  return `<button class="arena-card cursor-interaction" data-fantasy-pick="${key}" data-investor="${d.key}" data-tier="${d.tier}" aria-pressed="${d.key==='cathie'}" aria-label="Compare ${d.name}, ${titleCase(d.tier)} in the 2025 season"><span class="card-crown"><span class="card-gem" aria-hidden="true"></span><span class="rarity-word">${d.tier.toUpperCase()}</span><span class="card-gem" aria-hidden="true"></span></span><span class="hero-window"><span class="portrait" data-person="${d.key}"></span></span><span class="name-scroll"><strong>${d.name}</strong><small>${d.fund.toUpperCase()}</small></span><span class="card-stats"><span><b class="card-value">${fmt(d.value)}%</b><small>2025 RETURN</small></span><span><b class="card-gap">${fmt(d.gap)}</b><small>PP VS INDEX</small></span></span><span class="card-foot">SEASON 2025 · RANK 0${d.rank} / 04</span></button>`;
 }
 function inventoryMarkup(d,key) {
  return `<button class="inventory-row cursor-interaction" data-fantasy-pick="${key}" data-investor="${d.key}" data-tier="${d.tier}" aria-pressed="${d.key==='cathie'}" aria-label="Choose ${d.name}, ${titleCase(d.tier)}"><span class="portrait" data-person="${d.key}"></span><span class="inventory-copy"><strong>${d.name}</strong><small>${titleCase(d.tier)} · #0${d.rank}</small></span><span class="inventory-value">${fmt(d.value)}%</span></button>`;
 }
 root.querySelectorAll('[data-card-deck]').forEach(el=>el.innerHTML=gameRoster.map(d=>cardMarkup(d,el.dataset.cardDeck)).join(''));
 root.querySelectorAll('[data-feature-card]').forEach(el=>el.innerHTML=cardMarkup(gameById.cathie,el.dataset.featureCard));
 root.querySelectorAll('[data-inventory]').forEach(el=>el.innerHTML=gameRoster.map(d=>inventoryMarkup(d,el.dataset.inventory)).join(''));
 root.querySelectorAll('[data-podium]').forEach(el=>el.innerHTML=[gameById.joel,gameById.cathie,gameById.bill].map(d=>`<div class="podium-place" data-place="${d.rank}" data-tier="${d.tier}"><span class="podium-number">${d.rank===1?'I':d.rank===2?'II':'III'}</span>${cardMarkup(d,el.dataset.podium)}<span class="podium-plinth">${d.tier.toUpperCase()} · ${fmt(d.gap)} PP</span></div>`).join(''));
 root.querySelectorAll('[data-tier-rules]').forEach(el=>el.innerHTML=`<div class="tier-key"><span data-tier="legendary"><i></i>Legendary<small>≥10 pp</small></span><span data-tier="epic"><i></i>Epic<small>4–&lt;10 pp</small></span><span data-tier="rare"><i></i>Rare<small>0–&lt;4 pp</small></span><span data-tier="common"><i></i>Common<small>&lt;0 pp</small></span></div><details class="tier-rules"><summary>How the 2025 tiers work</summary><p>Season tiers use the 2025 return gap versus the S&amp;P 500 total-return index. They measure one year’s outperformance, not lifetime skill. Every card shows its vehicle; fund structures and risks differ. Tier thresholds are SPX Arena’s proposed scoring rules.</p></details>`);
 root.querySelectorAll('.missing-history').forEach(el=>el.innerHTML='<strong>Bill Ackman · PSH</strong><span>2025 NAV return: +20.9%<br>S&amp;P 500 total return: +17.9%<br>Benchmark gap: +3.0 percentage points.</span><span>A comparable 2021–2025 series is not available in this collection.</span>');
